# Generated by Django 4.0.1 on 2022-01-10 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipient', '0002_rename_donor_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=20)),
                ('request_initiate', models.BooleanField(default=False)),
                ('request_pending', models.BooleanField(default=False)),
                ('request_end', models.BooleanField(default=False)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipient.recipient')),
            ],
        ),
    ]
